import OpenAI, { toFile } from "openai";
import { zodTextFormat } from "openai/helpers/zod";
import { z } from "zod";
import type { LoadedImage } from "./images";
import { toDataUrl } from "./images";
import type { SceneSpec } from "./types";

let client: OpenAI | null = null;
function getClient() {
  if (!client) {
    const apiKey = process.env.OPENAI_API_KEY;
    if (!apiKey) throw new Error("OPENAI_API_KEY is not set");
    client = new OpenAI({ apiKey });
  }
  return client;
}

export const VISION_MODEL = process.env.OPENAI_VISION_MODEL || "gpt-5.4";
export const IMAGE_MODEL = process.env.OPENAI_IMAGE_MODEL || "gpt-image-2";

const PinRoleSchema = z.enum([
  "scene",
  "landmark",
  "detail",
  "material",
  "mood",
  "ignore",
]);

const SceneSpecSchema = z.object({
  world_title: z.string(),
  world_type: z.string(),
  style: z.string(),
  layout: z.string(),
  zones: z.array(z.object({ name: z.string(), description: z.string() })),
  materials: z.array(z.string()),
  palette: z.array(z.string()),
  key_objects: z.array(z.string()),
  avoid: z.array(z.string()),
  pins: z.array(
    z.object({
      index: z.number().int(),
      role: PinRoleSchema,
      scene_score: z.number(),
      summary: z.string(),
      contributes: z.array(z.string()),
    }),
  ),
  hero_pin_index: z.number().int(),
  reference_pin_indices: z.array(z.number().int()),
  world_text_prompt: z.string(),
  compose_prompt: z.string(),
});

const ANALYZE_SYSTEM = `You are a production designer turning a Pinterest mood board into ONE coherent, explorable 3D world.

The world will be generated by World Labs Marble from a single eye-level wide image plus a text prompt. Marble is good at: continuous outdoor/indoor spaces, ground + background + walkable path visible, consistent lighting. It is bad at: product close-ups, portraits, collages, floating objects, mixing cartoon with photoreal.

Your job:
1. Classify every pin (0-indexed, in the order given):
   - scene: wide view of a space, could directly seed the world. scene_score 7-10.
   - landmark: a notable feature that should physically exist in the world (a big tree, a pond, a hanging blanket).
   - detail: small props / tabletop items to place in the world.
   - material: only contributes fabrics, textures, palette.
   - mood: lighting / film grain / atmosphere reference.
   - ignore: portraits of people, product packaging, anything that should NOT become a thing in the world. People are never placed in the world; extract only their clothing colors/materials if useful.
   scene_score is 0-10 for "usable as a wide, eye-level scene image for a world generator" (ground, background and depth visible; not a close-up).
2. Decide world_title, world_type, style (one consistent rendering style, e.g. "photoreal with soft film grain, fairytale mood" — never mix stop-motion/cartoon with photoreal), layout (where things are relative to a viewer standing at the entrance), and 4-6 zones (entrance, center, left, right, back...).
3. hero_pin_index = the single best scene pin. reference_pin_indices = 3-5 pins for the image composer, hero first, then landmarks/details that must be visible.
4. world_text_prompt: 2-4 sentences for Marble describing the whole space, materials, palette, key objects, lighting and style. Concrete nouns, no people, no brand names.
5. compose_prompt: instructions for an image model that will be given the reference images and must paint ONE wide eye-level 3:2 scene (horizontal). Describe camera (eye level, wide angle, standing at the entrance looking in), what is at left/center/right/background, scale, lighting, style. Say explicitly: no people, no text, no logos, nothing floating, keep ground and sky/canopy visible, continuous space. Reference images by their visible content, not by number.
Be specific. Prefer the real details visible in the images (patterns, ceramics, fabrics) over generic adjectives.`;

export async function analyzeBoard(images: LoadedImage[]): Promise<SceneSpec> {
  const openai = getClient();
  const content: OpenAI.Responses.ResponseInputContent[] = [
    {
      type: "input_text",
      text: `Here are ${images.length} pins from one board, indexed 0..${images.length - 1} in order. Analyze them and return the scene spec.`,
    },
  ];
  images.forEach((img, i) => {
    content.push({ type: "input_text", text: `Pin ${i}:` });
    content.push({ type: "input_image", image_url: toDataUrl(img), detail: "low" });
  });

  const response = await openai.responses.parse({
    model: VISION_MODEL,
    instructions: ANALYZE_SYSTEM,
    input: [{ role: "user", content }],
    text: { format: zodTextFormat(SceneSpecSchema, "scene_spec") },
  });

  const spec = response.output_parsed;
  if (!spec) throw new Error("Model returned no parsed scene spec");

  // Sanity-clamp indices
  const n = images.length;
  const clamp = (i: number) => Math.max(0, Math.min(n - 1, i));
  spec.hero_pin_index = clamp(spec.hero_pin_index);
  spec.reference_pin_indices = Array.from(
    new Set([spec.hero_pin_index, ...spec.reference_pin_indices.map(clamp)]),
  ).slice(0, 5);
  spec.pins = spec.pins.filter((p) => p.index >= 0 && p.index < n);
  return spec;
}

/**
 * Compose a single wide scene image from reference pins using gpt-image edit.
 * Returns PNG bytes.
 */
export async function composeScene(
  references: LoadedImage[],
  spec: SceneSpec,
): Promise<Buffer> {
  const openai = getClient();
  const files = await Promise.all(
    references.map((img, i) =>
      toFile(img.bytes, `ref-${i}.${img.ext}`, { type: img.mime }),
    ),
  );

  const prompt = [
    `Create ONE new photograph-like image of an explorable outdoor space, using the attached images only as references for environment, objects, materials and color palette.`,
    `World: ${spec.world_title} — ${spec.world_type}. Style: ${spec.style}.`,
    `Layout: ${spec.layout}`,
    spec.zones.map((z) => `${z.name}: ${z.description}`).join(" | "),
    `Materials: ${spec.materials.join(", ")}. Palette: ${spec.palette.join(", ")}. Key objects: ${spec.key_objects.join(", ")}.`,
    spec.compose_prompt,
    `Hard rules: horizontal wide-angle composition at standing eye level; ground visible in the bottom third, tree canopy or sky visible at top; one continuous space with a clear walkable path; realistic object sizes; nothing floating; no people, no hands, no text, no logos, no packaging. Avoid: ${spec.avoid.join(", ")}.`,
  ].join("\n");

  const result = await openai.images.edit({
    model: IMAGE_MODEL,
    image: files,
    prompt,
    size: "1536x1024",
    quality: "high",
    input_fidelity: "high",
    output_format: "png",
  });

  const b64 = result.data?.[0]?.b64_json;
  if (!b64) throw new Error("Image model returned no image");
  return Buffer.from(b64, "base64");
}
